# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ce311c809e71ed860448b9fcd9d18b965092a8e9783475034634219fe878a6447d71b8d1ad78981e5a0f2e9a0b434df2d3d74ad421f95ee8f36f41142f2ecd9

test:
  secret_key_base: 26ce0df3d6a452fa5f1680d632f6b8666774443e5c08d5527eb4ea892d665d9deb39d46d9ae24c0ac7e5cbf07eb95ea2bebb6c2e3f673c05eb14f6ace1363754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

SENDGRID_USERNAME=app53530260@heroku.com
SENDGRID_PASSWORD=mibuzyat6857